services:
  - type: web
    name: hymovie-backend
    env: node
    region: singapore
    plan: free
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: TMDB_ACCESS_TOKEN
        value: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyYmNkMmRiMjI5NjEwOTk1OThmZTkzNzUxOTBmYzdmMiIsIm5iZiI6MTc1MzA3MjY3NC4wMzIsInN1YiI6IjY4N2RjNDIyNzU4N2M0MjIyYWY3NmM3OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.3-xBh6zZdg4hv_1jxuwxPbGUOPYxW7sVoHkABQzacNI
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3
      - key: TMDB_IMAGE_BASE_URL
        value: https://image.tmdb.org/t/p/w500
      - key: TMDB_BACKDROP_BASE_URL
        value: https://image.tmdb.org/t/p/original
      - key: VIDSRC_BASE_URL
        value: https://vidsrc.to/embed
